# Generated by Django 5.0.7 on 2024-08-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
